title: Gemmatech Homepage
author: Anna Kang
email: anna.kang@gemmatech.co.kr
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Gemmatech

twitter_username: gemmatech
github_username:  gemmatech

sass:
    style: compressed
